# This is a basic workflow to help you get started with Actions

name: tf-approval

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - feature/mpctf-137
    # paths:
    # - 'dev.yaml'
    # - '.github/workflows/main.yml'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  https:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: http request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://admin.sps.atos.net/api/CloudInventory/UpdateResourceData'
          method: 'POST'
          username: 'XYZ'
          password: '1234'
          files: ././dev.yaml.json
  