# This is a basic workflow to help you get started with Actions

name: tf-dummy
env:

  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUB_ID_LZ1 }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.DEV_SA_TOKEN }}
  SUB_ID_LZ1: ${{ secrets.SUB_ID_LZ1 }}
  TF_STATE_SA_RG_NAME: ${{ secrets.SA_RG_NAME }}
  TF_STATE_SA_NAME: ${{ secrets.SA_NAME }}
  TF_STATE_SA_CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
  
  issue_comment:
    types: [created]
    # paths:
    # - 'dev.yaml'
    # - '.github/workflows/main.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  approval_required_if_rc_gt_10:
    if: ${{ github.event.comment.body != 'Approved' }}
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    outputs:
      matrix: ${{ steps.validation.outputs.matrix }}
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install yq tool
        run: |
          wget --no-verbose --quiet https://github.com/mikefarah/yq/releases/download/v4.24.4/yq_linux_386.tar.gz -O - |\
          tar xz && sudo mv yq_linux_386 /usr/bin/yq
      - name: Install Python pip
        run: |
          sudo apt-get -qq -y update > /dev/null
          sudo apt-get -qq -y install python3-pip > /dev/null
          pip install pandas
          python ./py_scripts/create_module.py dev.yaml
          echo "$RES"
          echo "RES=$(python ./py_scripts/resource_validation.py)" >> $GITHUB_ENV                
      
      - name: Create an issue
        id: validation
        if: 3 > 2
        run: |
          echo "::set-output name=matrix::true"
      
        
  pending_for_approval:
    runs-on: ubuntu-latest
    needs: [approval_required_if_rc_gt_10]
    if: ${{ always() && needs.approval_required_if_rc_gt_10.outputs.matrix == 'true'}}
    defaults:
      run:
        shell: bash
    steps:
      - name: echo
        run: echo "Issue Created"
